"""foundation

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 11:22:00.001028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crm_client_id', sa.BigInteger(), nullable=True),
    sa.Column('primary_domain', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('crm_client_id', name=op.f('uq_clients_crm_client_id')),
    schema='seo'
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wp_user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'seo_manager', 'content_manager', 'designer', 'developer')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('wp_user_id', name=op.f('uq_users_wp_user_id')),
    schema='seo'
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['seo.users.id'], name=op.f('fk_app_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings')),
    schema='seo'
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('locations', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('content_language', sa.String(length=8), nullable=False),
    sa.Column('working_language', sa.String(length=8), nullable=False),
    sa.Column('business_services', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('business_goals', sa.Text(), nullable=False),
    sa.Column('conversion_goals', sa.Text(), nullable=False),
    sa.Column('excluded_topics', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('scope', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('on_hold', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('strategy_months', sa.Integer(), server_default='6', nullable=False),
    sa.Column('content_per_month', sa.Integer(), server_default='2', nullable=False),
    sa.Column('upsell_reminder_at', sa.Date(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'researching', 'ai_analysis_complete', 'seo_review', 'client_review', 'approved', 'production', 'completed')", name=op.f('ck_projects_status')),
    sa.ForeignKeyConstraint(['client_id'], ['seo.clients.id'], name=op.f('fk_projects_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['seo.users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    schema='seo'
    )
    op.create_index('ix_projects_owner', 'projects', ['owner_id'], unique=False, schema='seo')
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False, schema='seo')
    op.create_table('activity_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_activity_log_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['seo.users.id'], name=op.f('fk_activity_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log')),
    schema='seo'
    )
    op.create_index('ix_activity_project', 'activity_log', ['project_id', 'at'], unique=False, schema='seo')
    op.create_table('api_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('units', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_api_logs_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_logs')),
    schema='seo'
    )
    op.create_index('ix_api_logs_project', 'api_logs', ['project_id', 'created_at'], unique=False, schema='seo')
    op.create_table('intake_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('missing', 'requested', 'received', 'n_a')", name=op.f('ck_intake_items_status')),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_intake_items_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['seo.users.id'], name=op.f('fk_intake_items_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intake_items')),
    sa.UniqueConstraint('project_id', 'key', name='uq_intake_key'),
    schema='seo'
    )
    op.create_table('project_competitors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_project_competitors_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_competitors')),
    schema='seo'
    )
    op.create_index('uq_competitor_domain', 'project_competitors', ['project_id', sa.literal_column('lower(domain)')], unique=True, schema='seo')
    op.create_table('project_members',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['seo.users.id'], name=op.f('fk_project_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('pk_project_members')),
    schema='seo'
    )
    op.create_table('seed_keywords',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.CheckConstraint("kind IN ('service', 'customer_term', 'location', 'high_margin', 'excluded', 'product')", name=op.f('ck_seed_keywords_kind')),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_seed_keywords_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seed_keywords')),
    schema='seo'
    )
    op.create_index('uq_seed_keyword', 'seed_keywords', ['project_id', sa.literal_column('lower(keyword)')], unique=True, schema='seo')
    op.create_table('status_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_status_history_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['seo.users.id'], name=op.f('fk_status_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_history')),
    schema='seo'
    )
    op.create_index('ix_status_history_project', 'status_history', ['project_id', 'at'], unique=False, schema='seo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_status_history_project', table_name='status_history', schema='seo')
    op.drop_table('status_history', schema='seo')
    op.drop_index('uq_seed_keyword', table_name='seed_keywords', schema='seo')
    op.drop_table('seed_keywords', schema='seo')
    op.drop_table('project_members', schema='seo')
    op.drop_index('uq_competitor_domain', table_name='project_competitors', schema='seo')
    op.drop_table('project_competitors', schema='seo')
    op.drop_table('intake_items', schema='seo')
    op.drop_index('ix_api_logs_project', table_name='api_logs', schema='seo')
    op.drop_table('api_logs', schema='seo')
    op.drop_index('ix_activity_project', table_name='activity_log', schema='seo')
    op.drop_table('activity_log', schema='seo')
    op.drop_index('ix_projects_status', table_name='projects', schema='seo')
    op.drop_index('ix_projects_owner', table_name='projects', schema='seo')
    op.drop_table('projects', schema='seo')
    op.drop_table('app_settings', schema='seo')
    op.drop_table('users', schema='seo')
    op.drop_table('clients', schema='seo')
    # ### end Alembic commands ###
