"""research

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 11:54:04.605723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_files_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['seo.users.id'], name=op.f('fk_files_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    schema='seo'
    )
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name=op.f('ck_jobs_status')),
    sa.ForeignKeyConstraint(['created_by'], ['seo.users.id'], name=op.f('fk_jobs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    schema='seo'
    )
    op.create_index('ix_jobs_queue', 'jobs', ['status', 'id'], unique=False, schema='seo')
    op.create_table('style_guides',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_style_guides_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_style_guides')),
    schema='seo'
    )
    op.create_table('imports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('sheet', sa.String(length=255), nullable=False),
    sa.Column('header_row', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('column_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitor_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('ahrefs_keywords', 'ahrefs_matching_terms', 'ahrefs_organic', 'ahrefs_content_gap', 'gkp', 'house_research', 'screaming_frog', 'manual', 'dataforseo', 'ahrefs_api')", name=op.f('ck_imports_source')),
    sa.CheckConstraint("status IN ('preview', 'queued', 'running', 'done', 'failed')", name=op.f('ck_imports_status')),
    sa.ForeignKeyConstraint(['created_by'], ['seo.users.id'], name=op.f('fk_imports_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['seo.files.id'], name=op.f('fk_imports_file_id_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_imports_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imports')),
    schema='seo'
    )
    op.create_table('keywords',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('term', sa.String(length=512), nullable=False),
    sa.Column('term_normalized', sa.String(length=512), nullable=False),
    sa.Column('translation', sa.String(length=512), nullable=False),
    sa.Column('parent_topic', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('term_location', sa.String(length=128), nullable=False),
    sa.Column('modifier', sa.String(length=128), nullable=False),
    sa.Column('source_intents', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('serp_features', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('sources', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('first_import_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_import_id'], ['seo.imports.id'], name=op.f('fk_keywords_first_import_id_imports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_keywords_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords')),
    sa.UniqueConstraint('project_id', 'term_normalized', name='uq_keyword_term'),
    schema='seo'
    )
    op.create_index('ix_keywords_project', 'keywords', ['project_id'], unique=False, schema='seo')
    op.create_table('competitor_rankings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_own', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('traffic', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['seo.keywords.id'], name=op.f('fk_competitor_rankings_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_rankings')),
    sa.UniqueConstraint('keyword_id', 'domain', 'location', name='uq_ranking'),
    schema='seo'
    )
    op.create_table('keyword_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('kd', sa.Integer(), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('traffic_potential', sa.Integer(), nullable=True),
    sa.Column('competition', sa.String(length=32), nullable=False),
    sa.Column('trend', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['seo.keywords.id'], name=op.f('fk_keyword_metrics_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_metrics')),
    sa.UniqueConstraint('keyword_id', 'location', 'source', name='uq_metric'),
    schema='seo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_metrics', schema='seo')
    op.drop_table('competitor_rankings', schema='seo')
    op.drop_index('ix_keywords_project', table_name='keywords', schema='seo')
    op.drop_table('keywords', schema='seo')
    op.drop_table('imports', schema='seo')
    op.drop_table('style_guides', schema='seo')
    op.drop_index('ix_jobs_queue', table_name='jobs', schema='seo')
    op.drop_table('jobs', schema='seo')
    op.drop_table('files', schema='seo')
    # ### end Alembic commands ###
