"""intelligence

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 11:57:21.136615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_llm_cache')),
    schema='seo'
    )
    op.create_table('business_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('positioning', sa.Text(), nullable=False),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audiences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('differentiators', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('proof_assets', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('competitors_notes', sa.Text(), nullable=False),
    sa.Column('site_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['seo.users.id'], name=op.f('fk_business_profiles_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_business_profiles_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_profiles')),
    sa.UniqueConstraint('project_id', 'version', name='uq_profile_version'),
    schema='seo'
    )
    op.create_table('clusters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pillar', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('total_volume', sa.Integer(), nullable=False),
    sa.Column('target_page_id', sa.BigInteger(), nullable=True),
    sa.Column('cannibalization_rule', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ai', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_clusters_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_page_id'], ['seo.pages.id'], name=op.f('fk_clusters_target_page_id_pages'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clusters')),
    schema='seo'
    )
    op.create_index('ix_clusters_project', 'clusters', ['project_id'], unique=False, schema='seo')
    op.create_table('measurement_plan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('focus', sa.Text(), nullable=False),
    sa.Column('what', sa.Text(), nullable=False),
    sa.Column('where_measured', sa.Text(), nullable=False),
    sa.Column('success_signal', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('content_scope', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_measurement_plan_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurement_plan')),
    schema='seo'
    )
    op.create_index(op.f('ix_seo_measurement_plan_project_id'), 'measurement_plan', ['project_id'], unique=False, schema='seo')
    op.create_table('pages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('page_type', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=False),
    sa.Column('h1', sa.String(length=255), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('seo_goal', sa.Text(), nullable=False),
    sa.Column('cta_label', sa.String(length=255), nullable=False),
    sa.Column('cta_url', sa.String(length=512), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('redirect_to', sa.String(length=512), nullable=False),
    sa.Column('schema_types', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('word_count_min', sa.Integer(), nullable=True),
    sa.Column('word_count_max', sa.Integer(), nullable=True),
    sa.Column('local_variation', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ai', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("page_type IN ('home', 'service_hub', 'city_hub', 'city_service', 'service', 'category', 'product', 'pillar', 'article', 'case_study', 'support')", name=op.f('ck_pages_page_type')),
    sa.ForeignKeyConstraint(['parent_id'], ['seo.pages.id'], name=op.f('fk_pages_parent_id_pages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_pages_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('project_id', 'url', name='uq_page_url'),
    schema='seo'
    )
    op.create_index(op.f('ix_seo_pages_project_id'), 'pages', ['project_id'], unique=False, schema='seo')
    op.create_table('internal_links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('from_page_id', sa.BigInteger(), nullable=False),
    sa.Column('to_page_id', sa.BigInteger(), nullable=True),
    sa.Column('to_url', sa.String(length=512), nullable=False),
    sa.Column('anchor', sa.String(length=255), nullable=False),
    sa.Column('placement', sa.String(length=255), nullable=False),
    sa.Column('link_type', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('wireframe_section', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['from_page_id'], ['seo.pages.id'], name=op.f('fk_internal_links_from_page_id_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_internal_links_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_page_id'], ['seo.pages.id'], name=op.f('fk_internal_links_to_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internal_links')),
    schema='seo'
    )
    op.create_index(op.f('ix_seo_internal_links_project_id'), 'internal_links', ['project_id'], unique=False, schema='seo')
    op.create_table('keyword_analysis',
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('bucket', sa.String(length=16), nullable=False),
    sa.Column('modifiers', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('business_value', sa.Integer(), nullable=False),
    sa.Column('commercial_opportunity', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('cluster_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('ai', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("intent = '' OR intent IN ('informational', 'commercial_investigation', 'commercial', 'transactional', 'problem', 'navigational', 'mixed')", name=op.f('ck_keyword_analysis_intent')),
    sa.CheckConstraint("status IN ('suggested', 'accepted', 'overridden')", name=op.f('ck_keyword_analysis_status')),
    sa.ForeignKeyConstraint(['cluster_id'], ['seo.clusters.id'], name=op.f('fk_keyword_analysis_cluster_id_clusters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['keyword_id'], ['seo.keywords.id'], name=op.f('fk_keyword_analysis_keyword_id_keywords'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_keyword_analysis_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['seo.users.id'], name=op.f('fk_keyword_analysis_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('keyword_id', name=op.f('pk_keyword_analysis')),
    schema='seo'
    )
    op.create_index(op.f('ix_seo_keyword_analysis_project_id'), 'keyword_analysis', ['project_id'], unique=False, schema='seo')
    op.create_table('page_keywords',
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.CheckConstraint("role IN ('primary', 'secondary', 'supporting')", name=op.f('ck_page_keywords_role')),
    sa.ForeignKeyConstraint(['keyword_id'], ['seo.keywords.id'], name=op.f('fk_page_keywords_keyword_id_keywords'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['seo.pages.id'], name=op.f('fk_page_keywords_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id', 'keyword_id', name=op.f('pk_page_keywords')),
    schema='seo'
    )
    op.create_index('uq_page_primary', 'page_keywords', ['page_id'], unique=True, schema='seo', postgresql_where=sa.text("role = 'primary'"))
    op.create_index('uq_primary_keyword', 'page_keywords', ['keyword_id'], unique=True, schema='seo', postgresql_where=sa.text("role = 'primary'"))
    op.create_table('parked_topics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=True),
    sa.Column('term', sa.String(length=512), nullable=False),
    sa.Column('pillar', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommended_handling', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['seo.keywords.id'], name=op.f('fk_parked_topics_keyword_id_keywords'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_parked_topics_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parked_topics')),
    schema='seo'
    )
    op.create_index(op.f('ix_seo_parked_topics_project_id'), 'parked_topics', ['project_id'], unique=False, schema='seo')
    op.create_table('roadmap_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=True),
    sa.Column('cluster_id', sa.BigInteger(), nullable=True),
    sa.Column('keyword_id', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('pillar', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('related_keywords', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('location_context', sa.String(length=255), nullable=False),
    sa.Column('content_direction', sa.Text(), nullable=False),
    sa.Column('cta', sa.String(length=255), nullable=False),
    sa.Column('internal_links', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('social_hook', sa.Text(), nullable=False),
    sa.Column('cannibalization_rule', sa.Text(), nullable=False),
    sa.Column('client_input', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=16), nullable=False),
    sa.Column('ai', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['seo.users.id'], name=op.f('fk_roadmap_items_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cluster_id'], ['seo.clusters.id'], name=op.f('fk_roadmap_items_cluster_id_clusters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['keyword_id'], ['seo.keywords.id'], name=op.f('fk_roadmap_items_keyword_id_keywords'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['seo.pages.id'], name=op.f('fk_roadmap_items_page_id_pages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_roadmap_items_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_items')),
    schema='seo'
    )
    op.create_index('ix_roadmap_project', 'roadmap_items', ['project_id', 'month'], unique=False, schema='seo')
    op.create_table('paid_plan_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('roadmap_item_id', sa.BigInteger(), nullable=True),
    sa.Column('seo_role', sa.Text(), nullable=False),
    sa.Column('meta_creative', sa.Text(), nullable=False),
    sa.Column('paid_role', sa.Text(), nullable=False),
    sa.Column('search_target', sa.Text(), nullable=False),
    sa.Column('remarketing_next', sa.Text(), nullable=False),
    sa.Column('kpi', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_paid_plan_items_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_item_id'], ['seo.roadmap_items.id'], name=op.f('fk_paid_plan_items_roadmap_item_id_roadmap_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paid_plan_items')),
    schema='seo'
    )
    op.create_index(op.f('ix_seo_paid_plan_items_project_id'), 'paid_plan_items', ['project_id'], unique=False, schema='seo')
    op.create_table('wireframes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('roadmap_item_id', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('essence', sa.Text(), nullable=False),
    sa.Column('flow', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('word_count_min', sa.Integer(), nullable=True),
    sa.Column('word_count_max', sa.Integer(), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proof_requirements', sa.Text(), nullable=False),
    sa.Column('must_have', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('forbidden', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('visual_sequence', sa.Text(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ux_notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['seo.users.id'], name=op.f('fk_wireframes_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['seo.pages.id'], name=op.f('fk_wireframes_page_id_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_wireframes_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_item_id'], ['seo.roadmap_items.id'], name=op.f('fk_wireframes_roadmap_item_id_roadmap_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wireframes')),
    sa.UniqueConstraint('page_id', 'version', name='uq_wireframe_version'),
    schema='seo'
    )
    op.create_index(op.f('ix_seo_wireframes_project_id'), 'wireframes', ['project_id'], unique=False, schema='seo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_wireframes_project_id'), table_name='wireframes', schema='seo')
    op.drop_table('wireframes', schema='seo')
    op.drop_index(op.f('ix_seo_paid_plan_items_project_id'), table_name='paid_plan_items', schema='seo')
    op.drop_table('paid_plan_items', schema='seo')
    op.drop_index('ix_roadmap_project', table_name='roadmap_items', schema='seo')
    op.drop_table('roadmap_items', schema='seo')
    op.drop_index(op.f('ix_seo_parked_topics_project_id'), table_name='parked_topics', schema='seo')
    op.drop_table('parked_topics', schema='seo')
    op.drop_index('uq_primary_keyword', table_name='page_keywords', schema='seo', postgresql_where=sa.text("role = 'primary'"))
    op.drop_index('uq_page_primary', table_name='page_keywords', schema='seo', postgresql_where=sa.text("role = 'primary'"))
    op.drop_table('page_keywords', schema='seo')
    op.drop_index(op.f('ix_seo_keyword_analysis_project_id'), table_name='keyword_analysis', schema='seo')
    op.drop_table('keyword_analysis', schema='seo')
    op.drop_index(op.f('ix_seo_internal_links_project_id'), table_name='internal_links', schema='seo')
    op.drop_table('internal_links', schema='seo')
    op.drop_index(op.f('ix_seo_pages_project_id'), table_name='pages', schema='seo')
    op.drop_table('pages', schema='seo')
    op.drop_index(op.f('ix_seo_measurement_plan_project_id'), table_name='measurement_plan', schema='seo')
    op.drop_table('measurement_plan', schema='seo')
    op.drop_index('ix_clusters_project', table_name='clusters', schema='seo')
    op.drop_table('clusters', schema='seo')
    op.drop_table('business_profiles', schema='seo')
    op.drop_table('llm_cache', schema='seo')
    # ### end Alembic commands ###
