"""documents

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-26 12:17:41.312022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type IN ('seo_strategy', 'content_strategy', 'roadmap', 'wireframe_deck', 'dev_brief', 'writer_brief', 'designer_brief', 'seo_checklist', 'tech_audit')", name=op.f('ck_documents_doc_type')),
    sa.CheckConstraint("status IN ('draft', 'review', 'approved', 'sent')", name=op.f('ck_documents_status')),
    sa.ForeignKeyConstraint(['approved_by'], ['seo.users.id'], name=op.f('fk_documents_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['seo.users.id'], name=op.f('fk_documents_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_documents_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    schema='seo'
    )
    op.create_index('ix_documents_project', 'documents', ['project_id', 'doc_type'], unique=False, schema='seo')
    op.create_table('document_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['seo.documents.id'], name=op.f('fk_document_files_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['seo.files.id'], name=op.f('fk_document_files_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_files')),
    schema='seo'
    )
    op.create_table('reference_docs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['seo.files.id'], name=op.f('fk_reference_docs_file_id_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_docs')),
    schema='seo'
    )
    op.create_table('production_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=True),
    sa.Column('roadmap_item_id', sa.BigInteger(), nullable=True),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('done_when', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('crm_task_id', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('seo', 'writer', 'developer', 'designer')", name=op.f('ck_production_tasks_role')),
    sa.CheckConstraint("status IN ('todo', 'in_progress', 'review', 'done')", name=op.f('ck_production_tasks_status')),
    sa.ForeignKeyConstraint(['assignee_id'], ['seo.users.id'], name=op.f('fk_production_tasks_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['seo.documents.id'], name=op.f('fk_production_tasks_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['seo.pages.id'], name=op.f('fk_production_tasks_page_id_pages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_production_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_item_id'], ['seo.roadmap_items.id'], name=op.f('fk_production_tasks_roadmap_item_id_roadmap_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_tasks')),
    schema='seo'
    )
    op.create_index('ix_tasks_project', 'production_tasks', ['project_id', 'role'], unique=False, schema='seo')
    op.create_foreign_key(op.f('fk_clusters_target_page_id_pages'), 'clusters', 'pages', ['target_page_id'], ['id'], source_schema='seo', referent_schema='seo', ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_clusters_target_page_id_pages'), 'clusters', schema='seo', type_='foreignkey')
    op.drop_index('ix_tasks_project', table_name='production_tasks', schema='seo')
    op.drop_table('production_tasks', schema='seo')
    op.drop_table('reference_docs', schema='seo')
    op.drop_table('document_files', schema='seo')
    op.drop_index('ix_documents_project', table_name='documents', schema='seo')
    op.drop_table('documents', schema='seo')
    # ### end Alembic commands ###
