"""audit

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-26 12:39:16.636428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler_agents',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_crawler_agents')),
    schema='seo'
    )
    op.create_table('audit_topics',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.String(length=32), nullable=False),
    sa.Column('size', sa.String(length=2), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("size IN ('XL', 'M', 'S')", name=op.f('ck_audit_topics_size')),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_audit_topics_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['seo.users.id'], name=op.f('fk_audit_topics_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('project_id', 'topic', name=op.f('pk_audit_topics')),
    schema='seo'
    )
    op.create_table('crawl_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_url', sa.Text(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('agent', 'upload')", name=op.f('ck_crawl_runs_source')),
    sa.CheckConstraint("status IN ('draft', 'queued', 'running', 'importing', 'done', 'failed', 'cancelled')", name=op.f('ck_crawl_runs_status')),
    sa.ForeignKeyConstraint(['created_by'], ['seo.users.id'], name=op.f('fk_crawl_runs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_crawl_runs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_runs')),
    schema='seo'
    )
    op.create_index('ix_crawl_runs_project', 'crawl_runs', ['project_id', 'id'], unique=False, schema='seo')
    op.create_index('ix_crawl_runs_queue', 'crawl_runs', ['status', 'source'], unique=False, schema='seo')
    op.create_table('audit_findings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('topic', sa.String(length=32), nullable=False),
    sa.Column('issue_key', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('previous_count', sa.Integer(), nullable=True),
    sa.Column('urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'fixed', 'wontfix')", name=op.f('ck_audit_findings_status')),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_audit_findings_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['seo.crawl_runs.id'], name=op.f('fk_audit_findings_run_id_crawl_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['seo.production_tasks.id'], name=op.f('fk_audit_findings_task_id_production_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_findings')),
    sa.UniqueConstraint('project_id', 'issue_key', name='uq_finding_issue'),
    schema='seo'
    )
    op.create_index(op.f('ix_seo_audit_findings_project_id'), 'audit_findings', ['project_id'], unique=False, schema='seo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_audit_findings_project_id'), table_name='audit_findings', schema='seo')
    op.drop_table('audit_findings', schema='seo')
    op.drop_index('ix_crawl_runs_queue', table_name='crawl_runs', schema='seo')
    op.drop_index('ix_crawl_runs_project', table_name='crawl_runs', schema='seo')
    op.drop_table('crawl_runs', schema='seo')
    op.drop_table('audit_topics', schema='seo')
    op.drop_table('crawler_agents', schema='seo')
    # ### end Alembic commands ###
