"""collab

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-26 12:57:56.980818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=True),
    sa.Column('requested_from', sa.BigInteger(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('decided_by', sa.BigInteger(), nullable=True),
    sa.Column('decided_by_name', sa.String(length=255), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("stage IN ('internal', 'client')", name=op.f('ck_approvals_stage')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'changes_requested', 'cancelled')", name=op.f('ck_approvals_status')),
    sa.CheckConstraint("subject_type IN ('project', 'document', 'wireframe', 'page', 'roadmap_item', 'finding', 'task')", name=op.f('ck_approvals_subject_type')),
    sa.ForeignKeyConstraint(['decided_by'], ['seo.users.id'], name=op.f('fk_approvals_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_approvals_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['seo.users.id'], name=op.f('fk_approvals_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_from'], ['seo.users.id'], name=op.f('fk_approvals_requested_from_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('token', name=op.f('uq_approvals_token')),
    schema='seo'
    )
    op.create_index('ix_approvals_pending', 'approvals', ['status', 'stage'], unique=False, schema='seo')
    op.create_index('ix_approvals_subject', 'approvals', ['subject_type', 'subject_id'], unique=False, schema='seo')
    op.create_index(op.f('ix_seo_approvals_project_id'), 'approvals', ['project_id'], unique=False, schema='seo')
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('is_client', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("subject_type IN ('project', 'document', 'wireframe', 'page', 'roadmap_item', 'finding', 'task')", name=op.f('ck_comments_subject_type')),
    sa.ForeignKeyConstraint(['author_id'], ['seo.users.id'], name=op.f('fk_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['seo.comments.id'], name=op.f('fk_comments_parent_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_comments_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['seo.users.id'], name=op.f('fk_comments_resolved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments')),
    schema='seo'
    )
    op.create_index('ix_comments_subject', 'comments', ['subject_type', 'subject_id'], unique=False, schema='seo')
    op.create_index(op.f('ix_seo_comments_project_id'), 'comments', ['project_id'], unique=False, schema='seo')
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("email_status IN ('pending', 'sent', 'skipped', 'failed')", name=op.f('ck_notifications_email_status')),
    sa.CheckConstraint("kind IN ('approval_request', 'approval_decision', 'comment', 'mention', 'task_assigned', 'task_overdue', 'upsell', 'crawl', 'document')", name=op.f('ck_notifications_kind')),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_notifications_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['seo.users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    schema='seo'
    )
    op.create_index('ix_notifications_outbox', 'notifications', ['email_status'], unique=False, schema='seo')
    op.create_index('ix_notifications_user', 'notifications', ['user_id', 'read_at'], unique=False, schema='seo')
    op.add_column('production_tasks', sa.Column('overdue_notified_at', sa.DateTime(timezone=True), nullable=True), schema='seo')
    op.add_column('projects', sa.Column('upsell_notified_at', sa.DateTime(timezone=True), nullable=True), schema='seo')
    op.drop_constraint(op.f('ck_documents_doc_type'), 'documents', schema='seo', type_='check')
    op.create_check_constraint(op.f('ck_documents_doc_type'), 'documents', "doc_type IN ('seo_strategy', 'content_strategy', 'roadmap', 'wireframe_deck', 'dev_brief', 'writer_brief', 'designer_brief', 'seo_checklist', 'tech_audit', 'monthly_report')", schema='seo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_documents_doc_type'), 'documents', schema='seo', type_='check')
    op.create_check_constraint(op.f('ck_documents_doc_type'), 'documents', "doc_type IN ('seo_strategy', 'content_strategy', 'roadmap', 'wireframe_deck', 'dev_brief', 'writer_brief', 'designer_brief', 'seo_checklist', 'tech_audit')", schema='seo')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'upsell_notified_at', schema='seo')
    op.drop_column('production_tasks', 'overdue_notified_at', schema='seo')
    op.drop_index('ix_notifications_user', table_name='notifications', schema='seo')
    op.drop_index('ix_notifications_outbox', table_name='notifications', schema='seo')
    op.drop_table('notifications', schema='seo')
    op.drop_index(op.f('ix_seo_comments_project_id'), table_name='comments', schema='seo')
    op.drop_index('ix_comments_subject', table_name='comments', schema='seo')
    op.drop_table('comments', schema='seo')
    op.drop_index(op.f('ix_seo_approvals_project_id'), table_name='approvals', schema='seo')
    op.drop_index('ix_approvals_subject', table_name='approvals', schema='seo')
    op.drop_index('ix_approvals_pending', table_name='approvals', schema='seo')
    op.drop_table('approvals', schema='seo')
    # ### end Alembic commands ###
