"""ranking snapshots

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-26 14:29:59.630421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_snapshots',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('tracked', sa.Integer(), nullable=False),
    sa.Column('top3', sa.Integer(), nullable=False),
    sa.Column('top10', sa.Integer(), nullable=False),
    sa.Column('avg_position', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['seo.projects.id'], name=op.f('fk_ranking_snapshots_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'period', name=op.f('pk_ranking_snapshots')),
    schema='seo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranking_snapshots', schema='seo')
    # ### end Alembic commands ###
