"""mail: postafiókok, levelek, ügyfél-címek, aláírás-adatok; staff szerepkör

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-26 17:20:00.601754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_wp_user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('imap_security', sa.String(length=8), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_security', sa.String(length=8), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=False),
    sa.Column('sent_folder', sa.String(length=255), nullable=False),
    sa.Column('sync_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_accounts')),
    schema='seo'
    )
    op.create_index(op.f('ix_seo_mail_accounts_owner_wp_user_id'), 'mail_accounts', ['owner_wp_user_id'], unique=False, schema='seo')
    op.create_table('mail_contacts',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('crm_client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_mail_contacts')),
    schema='seo'
    )
    op.create_index(op.f('ix_seo_mail_contacts_crm_client_id'), 'mail_contacts', ['crm_client_id'], unique=False, schema='seo')
    op.create_table('mail_profiles',
    sa.Column('wp_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('wp_user_id', name=op.f('pk_mail_profiles')),
    schema='seo'
    )
    op.create_table('mail_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('folder', sa.String(length=8), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('in_reply_to', sa.String(length=512), nullable=False),
    sa.Column('references', sa.Text(), nullable=False),
    sa.Column('thread_key', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('to', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snippet', sa.String(length=300), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('crm_client_id', sa.Integer(), nullable=True),
    sa.Column('crm_task_id', sa.Integer(), nullable=True),
    sa.Column('sent_by_wp_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['seo.mail_accounts.id'], name=op.f('fk_mail_messages_account_id_mail_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_messages')),
    sa.UniqueConstraint('account_id', 'folder', 'uid', name='folder_uid'),
    schema='seo'
    )
    op.create_index('ix_mail_messages_list', 'mail_messages', ['account_id', 'folder', 'date'], unique=False, schema='seo')
    op.create_index('ix_mail_messages_msgid', 'mail_messages', ['account_id', 'message_id'], unique=False, schema='seo')
    op.create_index('ix_mail_messages_thread', 'mail_messages', ['account_id', 'thread_key'], unique=False, schema='seo')
    op.create_index(op.f('ix_seo_mail_messages_crm_client_id'), 'mail_messages', ['crm_client_id'], unique=False, schema='seo')
    op.create_index(op.f('ix_seo_mail_messages_date'), 'mail_messages', ['date'], unique=False, schema='seo')
    # ### end Alembic commands ###
    # Új szerepkör: CRM munkatárs (csak levelezés).
    op.drop_constraint(op.f('ck_users_role'), 'users', schema='seo', type_='check')
    op.create_check_constraint(op.f('ck_users_role'), 'users', "role IN ('admin', 'seo_manager', 'content_manager', 'designer', 'developer', 'staff')", schema='seo')


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM seo.users WHERE role = 'staff'")
    op.drop_constraint(op.f('ck_users_role'), 'users', schema='seo', type_='check')
    op.create_check_constraint(op.f('ck_users_role'), 'users', "role IN ('admin', 'seo_manager', 'content_manager', 'designer', 'developer')", schema='seo')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_mail_messages_date'), table_name='mail_messages', schema='seo')
    op.drop_index(op.f('ix_seo_mail_messages_crm_client_id'), table_name='mail_messages', schema='seo')
    op.drop_index('ix_mail_messages_thread', table_name='mail_messages', schema='seo')
    op.drop_index('ix_mail_messages_msgid', table_name='mail_messages', schema='seo')
    op.drop_index('ix_mail_messages_list', table_name='mail_messages', schema='seo')
    op.drop_table('mail_messages', schema='seo')
    op.drop_table('mail_profiles', schema='seo')
    op.drop_index(op.f('ix_seo_mail_contacts_crm_client_id'), table_name='mail_contacts', schema='seo')
    op.drop_table('mail_contacts', schema='seo')
    op.drop_index(op.f('ix_seo_mail_accounts_owner_wp_user_id'), table_name='mail_accounts', schema='seo')
    op.drop_table('mail_accounts', schema='seo')
    # ### end Alembic commands ###
